# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  robotiq_2f140_left_inner_finger_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 2
  robotiq_2f142_left_inner_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 2
  robotiq_2f142_left_outer_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 2
  robotiq_2f142_right_inner_finger_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 2
  robotiq_2f142_right_inner_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 2
  robotiq_2f142_right_outer_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 2
  ur3_elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: true
    max_acceleration: 13.9626 # 800 deg/s^2
  ur3_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: true
    max_acceleration: 13.9626
  ur3_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: true
    max_acceleration: 13.9626
  ur3_wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 6.283185307179586
    has_acceleration_limits: true
    max_acceleration: 13.9626
  ur3_wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 6.283185307179586
    has_acceleration_limits: true
    max_acceleration: 13.9626
  ur3_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 6.283185307179586
    has_acceleration_limits: true
    max_acceleration: 13.9626
