controller_list:
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - robotiq_2f140_left_outer_knuckle_joint
  - name: eef_gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - ur3_shoulder_pan_joint
      - ur3_shoulder_lift_joint
      - ur3_elbow_joint
      - ur3_wrist_1_joint
      - ur3_wrist_2_joint
      - ur3_wrist_3_joint
  - name: eef_pipette_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - ur3_shoulder_pan_joint
      - ur3_shoulder_lift_joint
      - ur3_elbow_joint
      - ur3_wrist_1_joint
      - ur3_wrist_2_joint
      - ur3_wrist_3_joint
