mesh_files:
  base:
    visual:
      mesh: "package://ur_description/meshes/ur3/visual/base.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://oscar_robot_setup_description/meshes/ur3/collision/vhacd_h16/base.stl"

  shoulder:
    visual:
      mesh: "package://ur_description/meshes/ur3/visual/shoulder.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://oscar_robot_setup_description/meshes/ur3/collision/vhacd_h16/shoulder.stl"

  upper_arm:
    visual:
      mesh: "package://ur_description/meshes/ur3/visual/upperarm.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://oscar_robot_setup_description/meshes/ur3/collision/vhacd_h16/upperarm.stl"

  forearm:
    visual:
      mesh: "package://ur_description/meshes/ur3/visual/forearm.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://oscar_robot_setup_description/meshes/ur3/collision/vhacd_h16/forearm.stl"

  wrist_1:
    visual:
      mesh: "package://ur_description/meshes/ur3/visual/wrist1.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://oscar_robot_setup_description/meshes/ur3/collision/vhacd_h16/wrist1.stl"
    visual_offset: -0.085

  wrist_2:
    visual:
      mesh: "package://ur_description/meshes/ur3/visual/wrist2.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://oscar_robot_setup_description/meshes/ur3/collision/vhacd_h16/wrist2.stl"
    visual_offset: -0.085

  wrist_3:
    visual:
      mesh: "package://ur_description/meshes/ur3/visual/wrist3.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://oscar_robot_setup_description/meshes/ur3/collision/vhacd_h16/wrist3.stl"
    visual_offset: -0.082
